name: Sync haki to lbrss

on:
  workflow_dispatch:

jobs:
  sync-haki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo (lbrss/lbracketstringingservices)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone haki repository
        run: |
          git clone https://github.com/haki-tech/lbrss2.git haki-source

      - name: Clean up unwanted files and folders
        run: |
          rm -f haki-source/next.config.ts
          rm -f haki-source/README.md
          rm -f haki-source/public/site.webmanifest
          rm -f haki-source/public/CNAME
          rm -rf haki-source/.github
          rm -rf haki-source/.git

          # Entferne alle versteckten Dateien und Ordner im haki-source Verzeichnis
          rm -rf haki-source/.* 2> /dev/null || true

      - name: Prepare snapshot after cleanup
        run: |
          cp -r haki-source haki-snapshot

      - name: Synchronize files from snapshot to target repo
        run: |
          rsync -av --delete haki-snapshot/ ./

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync from haki-tech at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push
          fi
