name: Sync from haki-tech

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout lbrss (Ziel-Repo)
        uses: actions/checkout@v4

      - name: Checkout haki-tech (Source-Repo)
        uses: actions/checkout@v4
        with:
          repository: kjhgithub/lbrss2
          path: haki-source
          # token: ${{ secrets.HAKI_PAT }} # Personal Access Token mit read access auf haki-tech

      - name: Synchronize files from haki to lbrss
        run: |
          rsync -av --delete \
            --exclude='.*' \
            --exclude='next.config.ts' \
            --exclude='README.md' \
            --exclude='public/site.webmanifest' \
            --exclude='public/CNAME' \
            haki-source/ ./

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Sync from haki-tech at $(date -u +"%Y-%m-%d %H:%M:%S UTC") (Automated)"
          git push
