name: Sync haki to lbrss

on:
  workflow_dispatch:

jobs:
  sync-haki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo (lbrss/lbracketstringingservices)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Clone source repo (kjhgithub/lbrss2)
        run: |
          git clone https://github.com/kjhgithub/lbrss2.git haki-source

      - name: Clean up unwanted files and folders in haki-source
        run: |
          rm -f haki-source/next.config.ts
          rm -f haki-source/README.md
          rm -f haki-source/public/site.webmanifest
          rm -f haki-source/public/CNAME
          rm -rf haki-source/.github
          rm -rf haki-source/.git
          find haki-source -mindepth 1 -maxdepth 1 -name ".*" -exec rm -rf {} +

      - name: Copy cleaned files from haki-source to target repo
        run: |
          cp -r haki-source/. .

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync from kjhgithub/lbrss2 at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push
          fi
